### ISSUE TITLE
Problem with building the Mac app

### ISSUE THREAD

**Issue by TheJacobHill** [TheJacobHill/Differential-Design#1]
Hi there,

I'm building a program in python and I've encountered a problem with building the Mac app. After several hours of looking for information and trying bunch of stuff, I haven't found anything that would work or at least change the error so I could work from that.

The terminal command:
`python3 setup.py py2app`
(?) the `python3 setup.py py2app -A` demo setup works just fine

The error using a py2app module:
```
Traceback (most recent call last):
  File "---my_setup_file_dictionary_path---/setup.py", line 63, in <module>
    setup(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/py2app/build_app.py", line 984, in run
    self._run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/py2app/build_app.py", line 1214, in _run
    self.run_normal()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/py2app/build_app.py", line 1326, in run_normal
    pkgdirs = self.collect_packagedirs()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/py2app/build_app.py", line 1290, in collect_packagedirs
    [
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/py2app/build_app.py", line 1291, in <listcomp>
    os.path.join(os.path.realpath(self.get_bootstrap(pkg)), "")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 394, in realpath
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType
``` 

My setup file:
```python
import py2app.recipes
import py2app.build_app

from setuptools import find_packages, setup

# pkgs = find_packages(".")

# class recipe_plugin(object):
#     @staticmethod
#     def check(py2app_cmd, modulegraph):
#         local_packages = pkgs[:]
#         local_packages += ['pygame', 'typing', 'os', 'copy', 'time', 'math', '__future__', 'json', 'threading']
#         return {
#             "packages": local_packages,
#         }

# py2app.recipes.my_recipe = recipe_plugin

APP = ['main.py']
DATA_FILES = ['all_of_the_necessary_files']
OPTIONS = {
    "packages": ['pygame', 'typing', 'os', 'copy', 'time', 'math', '__future__', 'json', 'threading']
}
OPTIONS.update(
    iconfile="icon/Icon.icns",
    plist=dict(CFBundleIdentifier='com.example.jacob')
)

setup(
    name="Differential Design",
    app=APP,
    data_files=DATA_FILES,
    include_package_data=True,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    # packages=pkgs,
    package_data={
        "": ["*.gal" , "*.gif" , "*.html" , "*.jar" , "*.js" , "*.mid" ,
             "*.png" , "*.py" , "*.pyc" , "*.sh" , "*.tmx" , "*.ttf" ,
             # "*.xcf",
             "*.json"
        ]
    },
)
``` 

Originally I've tried the commented part, but found out the shorter version works just as good.

Based on the error message, I suppose it has something to do with the imported packages. Though I've triple checked and I'm importing all my local modules from all my imported data files, so there shouldn't be problem there.

Does anyone know what the issue is?

Thank You in advance for Your reply,
Jacob

**Comment by TheJacobHill** [comment]
Sorry for the code style, it's my first issue. Glad to change it if you know a way to fix it.

**Comment by TheJacobHill** [comment]
Anyways..

It seems I got it working in the end.
Just in case anyone finds himself having the same problem and stumbles upon my issue here.. here is the solution I found myself having no issue with.

I just basically had some problem with my 'setup.py', and here is the version that works for me:
```python
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('data_handler', [
        'data_handler/data.py',
        'data_handler/localization.json']),
    ('gui/fonts', [
        'gui/fonts/pixel_font.ttf',
        'gui/fonts/time_digits_font.ttf']),
    ('gui/text', [
        'gui/text/cutscenes.json',
        'gui/text/cutscenes.py',
        'gui/text/text_screen.py']),
    ('gui', [
        'gui/loading_screen.py',
        'gui/menu.py',
        'gui/view.py']),
    ('icon', [
        'icon/icon.png']),
    ('parts', [
        'parts/bearing.py',
        'parts/bearings_data.py',
        'parts/carrier.py',
        'parts/differential.py',
        'parts/gear.py',
        'parts/part.py',
        'parts/shaft.py',
        'parts/threads_data.py']),
    ('save_data', [
        'save_data/general.json']),
    'file_handler.py',
    'LaTeX.py',
    'print_handler.py',
    'render.py',
    'settings.py',
    'text.py',
    'variable.py']
OPTIONS = {}
OPTIONS.update(
    iconfile="icon/icon.icns",
    plist=dict(CFBundleIdentifier='com.example.jacob')
)

setup(
    name="Differential Design",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
```

**Comment by TheJacobHill** [comment]
Anyways..

It seems I got it working in the end.
Just in case anyone finds himself having the same problem and stumbles upon my issue here.. here is the solution I found myself having no issue with.

I just basically had some problem with my 'setup.py', and here is the version that works for me:
```python
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['all_of_the_necessay_files']
OPTIONS = {}
OPTIONS.update(
    iconfile="icon/icon.icns",
    plist=dict(CFBundleIdentifier='com.example.jacob')
)

setup(
    name="Differential Design",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
``` 
py2app basically seems to find all the necessary modules/packages itself and I just made the whole process harder for him with my initial 'setup.py' file configuration
That's my conclusion

Have a nice rest of Your day,
Jacob
